export * from './addressComparison';
export { formatAddress } from './addressFormatting';
export * from './addressFromPublicKey';
export * from './addressPredicates';
export * from './checkAddressForErrors';
export * from './encoding';
export * from './errors';
export * from './test.constants';
export * from './parseWalletAddress';
export * from './protocols';
export * from './nameServiceAddress';
export type { NameServiceAddress as MailchainAddress } from './nameServiceAddress';
export * from './walletAddress';
